Verify firing error event behaviors in Worker when close() is called from onerror.

On success, you will see a series of "PASS" messages, followed by "TEST COMPLETE".

Starting worker: resources/connect-error-by-no-websocket-server-closeonerror.js
[Worker] Test start (Port 8892)
PASS [Worker] onerror was called
PASS [Worker] onclose was called
PASS successfullyParsed is true

TEST COMPLETE

